# OperatorGroup - must be AllNamespaces for Red Hat operator
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: cm-operator-group
  namespace: cert-manager-operator
  #annotations:
  #  argocd.argoproj.io/sync-wave: "-2"
spec: {}  # AllNamespaces install mode
---
# Subscription to Red Hat External Secrets Operator
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cert-manager-operator
  namespace: cert-manager-operator
spec:
  channel: stable-v1
  installPlanApproval: Automatic
  name: cert-manager-operator
  source: cm-custom-index-3
  sourceNamespace: openshift-marketplace
---
apiVersion: cert-manager.io/v1
kind: Issuer 
metadata:
  name: selfsigned
  namespace: istio-system
  annotations:
    #argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true  
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-ca
  namespace: istio-system
  annotations:
    #argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true  
spec:
  isCA: true
  duration: 87600h # 10 years
  secretName: istio-ca
  commonName: istio-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  subject:
    organizations:
      - cluster.local
      - cert-manager
  issuerRef:
    name: selfsigned
    kind: Issuer 
    group: cert-manager.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-cert-manager-creator
  namespace: istio-system
rules:
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  - issuers
  - certificaterequests
  verbs:
  - create
  - get
  - update
  - delete
  - patch
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-cert-manager-binding
  namespace: istio-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-cert-manager-creator
subjects:
- kind: ServiceAccount
  # Replace 'openshift-gitops-argocd-application-controller' with the actual SA name if different
  name: openshift-gitops-argocd-application-controller 
  namespace: openshift-gitops # The namespace where the ServiceAccount lives
---  
apiVersion: cert-manager.io/v1
kind: Issuer 
metadata:
  name: selfsigned
  namespace: istio-system
  annotations:
    #argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true  
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-ca
  namespace: istio-system
  annotations:
    #argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true  
spec:
  isCA: true
  duration: 87600h # 10 years
  secretName: istio-ca
  commonName: istio-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  subject:
    organizations:
      - cluster.local
      - cert-manager
  issuerRef:
    name: selfsigned
    kind: Issuer 
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: istio-ca
  namespace: istio-system
  annotations:
    #argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true  
spec:
  ca:
    secretName: istio-ca
---
apiVersion: operator.openshift.io/v1alpha1
kind: IstioCSR
metadata:
  name: default
  namespace: istio-system
  annotations:
    #argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true  
spec:
  istioCSRConfig:
    certManager:
      issuerRef:
        name: istio-ca
        kind: Issuer
        group: cert-manager.io
    istiodTLSConfig:
      trustDomain: cluster.local
    istio:
      namespace: istio-system
---

